### ISSUE TITLE
Not able to train the bot

### ISSUE THREAD

**Issue by Juggernaut1997** [RasaHQ/medicare_locator#60]
Command - $make train-core
Output - 
python3 -m rasa_core.train -d domain.yml -s data/core -o models/current/dialogue -c core_config.yml
make: *** [train-core] Error 9009

Except this i am not getting any detail info

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
@Juggernaut1997 What rasa version are you using? What operating system do you use? Can you please run the command in debug mode (`--debug`) and share the log output here? Thanks.

**Comment by HarshitaSahai** [comment]
@sara-tagger                                                                                                                                                
Use the command in Makefile i.e 
$ python3  -m rasa_nlu.train -c nlu_config.yml --data data/nlu_data.md -o models --fixed_model_name nlu --project current --verbose

python3 (if this is the name for your .exe then okay else change that as well)

**Comment by Juggernaut1997** [comment]
It worked. Thanks! :)
