### ISSUE TITLE
Error Anaconda

### ISSUE THREAD

**Issue by HarshitaSahai** [RasaHQ/medicare_locator#61]
python3 -m rasa_core.train -d domain.yml -s data/core -o models/current/dialogue -c core_config.yml
make: *** [train-core] Error 9009

Python 3.6
Windows 10

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alwx will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
